### ISSUE TITLE
Can you add a option to add photos to the post

### ISSUE THREAD

**Issue by salvecom333** [1Loaf-of-Bread/MassFacebookGroupPoster#1]
I tried a couple ways to add the photo, but to no avail.
the following is a portion of my failed attemps:
`#file_input = browser.find_element(By.XPATH, '//input[@type="file"]')
            # image_path = r'C:\MassFacebookGroupPoster\images\firsttest.png'

            # file_input = browser.find_element(By.CSS_SELECTOR, 'input[type="file"]')

            # # Send the absolute file path to the file input element
            # file_input.send_keys(image_path)
            # sleep(10)
            

			
            
            # Send the image file path to the file input element
            # file_input.send_keys('C:/MassFacebookGroupPoster/images/firsttest.png')

            # # Wait for a few seconds
            # time.sleep(2)
            
            
            # photosend = browser.find_element(By.XPATH, "//input[@type='file']")
            # photosend.send_keys('C:/MassFacebookGroupPoster/images/firsttest.png')
            
            # sendPhoto = browser.find_element(By.CLASS_NAME, "x1s85apg")
            # sendPhoto.send_keys('C:/MassFacebookGroupPoster-1.1.1/images/firsttest.png')
            # sleep(1)
            
            # file_input = browser.find_element(By.CSS_SELECTOR, 'input[type="file"]')
            

            #     # Send the image file path to the file input element
            # file_input.send_keys('C:/MassFacebookGroupPoster/images/firsttest.png')

            #     # Wait for a few seconds
            # sleep(5)

            #     # Click add image
            #     imgLoc = "C:\\Users\\blank\\Desktop\\Marketing_Campaign\\MassFacebookGroupPoster-1.1.1\\"+imgFolder+"\\"+images[i]
            #     tagName = 'file'+str(i%3+1)
            #     buttons = browser.find_elements(By.NAME, tagName)

            #     buttons[0].send_keys(imgLoc)
            #     if i % 3 - 2 == 0 or i == len(images) - 1:
            #         browser.find_element(By.NAME, 'add_photo_done').click()

            # sleep(1)`

how can a add images to the post, thank you for creating this! I have spent a whole afternoon with this since yesterday and i can't add images. I have like two to three pages of failed attempts.

**Comment by 1Loaf-of-Bread** [comment]
Hey, thank you for reaching out to me.

Don't worry, this is an amazing recommendation and I'll try to get this done as soon as possible.

Expect an update on the program! ^~^

Once the program is updated I will close this thread with a notification for you.

Thank you!

**Comment by salvecom333** [comment]
Thank you 🍞 loaf!

**Comment by 1Loaf-of-Bread** [comment]
@salvecom333 I have released a new update, v1.2.0.

Please read the new section added in README.md "Adding an Image to Post:", there it explains everything you need to know.

Please let me know if you have any issues.

Thank you again for the suggestion!
Loaf

**Comment by salvecom333** [comment]
God bless you man. You are fast as lightning! I am so broke right now, but
when i do start getting revenue for some of my projects i would like to buy
you a coffee. Add a donation link in your profile for people that will like
to show their appreciation to you loaf. Thanks again loaf, you saved me
from alot of headaches, and i won't forget.

-Salvador

**Comment by 1Loaf-of-Bread** [comment]
@salvecom333 Thank you so much man, reading this has made my day happy!

I have never thought of accepting donations as thanks for my projects, I will add my Ko-fi link. Also, I wish you the best for your projects!

Thank you again, I am so glad to hear that my program is useful to you, you put a smile on my face ^~^

I wish you an amazing day!!
