### ISSUE TITLE
TypeError: WebDriver.__init__() got an unexpected keyword argument 'chrome_options'

### ISSUE THREAD

**Issue by TheDescar** [1Loaf-of-Bread/MassFacebookGroupPoster#2]
Hello 

I have installed all the requirements and after choosing the group I type: ':p' and get something like this:

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\MassFacebook\MFGP.py", line 315, in <module>
    failCount, count = sendToGroups(postText, groups)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Desktop\MassFacebook\MFGP.py", line 234, in sendToGroups    
    browser = webdriver.Chrome(chrome_options=chrome_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'chrome_options'

On line 234
I changed "browser = webdriver.Chrome(chrome_options=chrome_options)"
            to: "browser = webdriver.Chrome(options=chrome_options)"

It starts but then I get even more errors.
Can you tell me what should I do?

Thanks
Regards!

**Comment by TheDescar** [comment]
Hello   Same issue,    Traceback (most recent call last):     File &#34;c:\Users\Admin\Desktop\MassFacebook2\MFGP.py&#34;, line 317, in &lt;module&gt;         failCount, count = sendToGroups(postText, groups)                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    File &#34;c:\Users\Admin\Desktop\MassFacebook2\MFGP.py&#34;, line 236, in sendToGroups      browser = webdriver.Chrome(service=service, chrome_option=chrome_options)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      TypeError: WebDriver.__init__() got an unexpected keyword argument &#39;chrome_option&#39;    and when I change     browser   =   webdriver . Chrome ( service = service ,  chrome_option = chrome_options )    browser   =   webdriver . Chrome ( service = service ,  option = chrome_options )   it starts, opens chrome browser, but nothing happens and it close the browser after few seconds,  thanks for trying to solve the problem.   Regards! 
     
      
       
        Dnia 18 sierpnia 2023 19:08 Loaf ***@***.***&gt; napisał(a):
       
    
       
         
 Hey there, 
 I&#39;m sorry about this error that has occurred. I just released MFGP v1.2.2 which should have fixed the error. Please let me know if this has resolved the errors you are having or if any more appear, I won&#39;t close this issue until then, or until 24 hours have passed. 
 Thank you!

**Comment by 1Loaf-of-Bread** [comment]
I am very sorry about this, please try the new edited MFGP v1.2.2 release

**Comment by 1Loaf-of-Bread** [comment]
@TheDescar Has the issue been fixed? I am going to have to close this issue within the next 12 hours if no response is submitted.

**Comment by TheDescar** [comment]
Hi, it was the weekend and I wasn&#39;t at the computer, I tried your latest release and this was my answer that I still have the same problem despite the code about &#34;service&#34;, maybe I&#39;m missing some components. Regards!  
     
      
       
        Dnia 20 sierpnia 2023 18:08 Loaf ***@***.***&gt; napisał(a):
       
    
       
         
 Closed  github.com #2  as completed.
